### ISSUE TITLE
Mishandled error

### ISSUE THREAD

**Issue by blackn0te** [Kool-Koder/eCTF-open-source#12]
![defaulterror](https://user-images.githubusercontent.com/33929865/54867182-3b8e1800-4db8-11e9-9a00-0e0756bd9d16.PNG)
Mishandled Error.

**Comment by blackn0te** [comment]
1. When joining a CTF group
2. Submitting forgot password request without inputting any email or whatsoever
3. -

**Comment by Kool-Koder** [comment]
Issued 2 more updates c75c798 & c861c87. Closing this issue as most bugs fixed. Found 1 new error to be causing some issues after migration from .NET Core 2.1 to 2.2. Will open a separate issue to trace this error.
